# Generated by Django 3.2.15 on 2023-07-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=16, unique=True)),
                ('user_name', models.CharField(max_length=16)),
                ('user_email', models.CharField(max_length=32, unique=True)),
                ('user_password', models.CharField(max_length=32)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
